/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PostsPageRouteImport } from './routes/PostsPage'
import { Route as CreatePostFormPageRouteImport } from './routes/CreatePostFormPage'
import { Route as IndexRouteImport } from './routes/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPageRoute = PostsPageRouteImport.update({
  id: '/PostsPage',
  path: '/PostsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePostFormPageRoute = CreatePostFormPageRouteImport.update({
  id: '/CreatePostFormPage',
  path: '/CreatePostFormPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/CreatePostFormPage': typeof CreatePostFormPageRoute
  '/PostsPage': typeof PostsPageRoute
  '/about': typeof AboutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/CreatePostFormPage': typeof CreatePostFormPageRoute
  '/PostsPage': typeof PostsPageRoute
  '/about': typeof AboutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/CreatePostFormPage': typeof CreatePostFormPageRoute
  '/PostsPage': typeof PostsPageRoute
  '/about': typeof AboutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/CreatePostFormPage' | '/PostsPage' | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/CreatePostFormPage' | '/PostsPage' | '/about'
  id: '__root__' | '/' | '/CreatePostFormPage' | '/PostsPage' | '/about'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatePostFormPageRoute: typeof CreatePostFormPageRoute
  PostsPageRoute: typeof PostsPageRoute
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PostsPage': {
      id: '/PostsPage'
      path: '/PostsPage'
      fullPath: '/PostsPage'
      preLoaderRoute: typeof PostsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CreatePostFormPage': {
      id: '/CreatePostFormPage'
      path: '/CreatePostFormPage'
      fullPath: '/CreatePostFormPage'
      preLoaderRoute: typeof CreatePostFormPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatePostFormPageRoute: CreatePostFormPageRoute,
  PostsPageRoute: PostsPageRoute,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
