/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteRouteImport } from './routes/authenticatedRoute/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as AuthenticatedRouteCreatePostRouteImport } from './routes/authenticatedRoute/createPost'
import { Route as AuthenticatedRouteEditPostPostIdRouteImport } from './routes/authenticatedRoute/editPost/$postId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRouteRoute = AuthenticatedRouteRouteRouteImport.update({
  id: '/authenticatedRoute',
  path: '/authenticatedRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteCreatePostRoute =
  AuthenticatedRouteCreatePostRouteImport.update({
    id: '/createPost',
    path: '/createPost',
    getParentRoute: () => AuthenticatedRouteRouteRoute,
  } as any)
const AuthenticatedRouteEditPostPostIdRoute =
  AuthenticatedRouteEditPostPostIdRouteImport.update({
    id: '/editPost/$postId',
    path: '/editPost/$postId',
    getParentRoute: () => AuthenticatedRouteRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticatedRoute': typeof AuthenticatedRouteRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/authenticatedRoute/createPost': typeof AuthenticatedRouteCreatePostRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/authenticatedRoute/editPost/$postId': typeof AuthenticatedRouteEditPostPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticatedRoute': typeof AuthenticatedRouteRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/authenticatedRoute/createPost': typeof AuthenticatedRouteCreatePostRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/authenticatedRoute/editPost/$postId': typeof AuthenticatedRouteEditPostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authenticatedRoute': typeof AuthenticatedRouteRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/authenticatedRoute/createPost': typeof AuthenticatedRouteCreatePostRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/authenticatedRoute/editPost/$postId': typeof AuthenticatedRouteEditPostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticatedRoute'
    | '/about'
    | '/login'
    | '/register'
    | '/authenticatedRoute/createPost'
    | '/posts/$postId'
    | '/posts'
    | '/authenticatedRoute/editPost/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticatedRoute'
    | '/about'
    | '/login'
    | '/register'
    | '/authenticatedRoute/createPost'
    | '/posts/$postId'
    | '/posts'
    | '/authenticatedRoute/editPost/$postId'
  id:
    | '__root__'
    | '/'
    | '/authenticatedRoute'
    | '/about'
    | '/login'
    | '/register'
    | '/authenticatedRoute/createPost'
    | '/posts/$postId'
    | '/posts/'
    | '/authenticatedRoute/editPost/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRouteRoute: typeof AuthenticatedRouteRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticatedRoute': {
      id: '/authenticatedRoute'
      path: '/authenticatedRoute'
      fullPath: '/authenticatedRoute'
      preLoaderRoute: typeof AuthenticatedRouteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticatedRoute/createPost': {
      id: '/authenticatedRoute/createPost'
      path: '/createPost'
      fullPath: '/authenticatedRoute/createPost'
      preLoaderRoute: typeof AuthenticatedRouteCreatePostRouteImport
      parentRoute: typeof AuthenticatedRouteRouteRoute
    }
    '/authenticatedRoute/editPost/$postId': {
      id: '/authenticatedRoute/editPost/$postId'
      path: '/editPost/$postId'
      fullPath: '/authenticatedRoute/editPost/$postId'
      preLoaderRoute: typeof AuthenticatedRouteEditPostPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteRouteChildren {
  AuthenticatedRouteCreatePostRoute: typeof AuthenticatedRouteCreatePostRoute
  AuthenticatedRouteEditPostPostIdRoute: typeof AuthenticatedRouteEditPostPostIdRoute
}

const AuthenticatedRouteRouteRouteChildren: AuthenticatedRouteRouteRouteChildren =
  {
    AuthenticatedRouteCreatePostRoute: AuthenticatedRouteCreatePostRoute,
    AuthenticatedRouteEditPostPostIdRoute:
      AuthenticatedRouteEditPostPostIdRoute,
  }

const AuthenticatedRouteRouteRouteWithChildren =
  AuthenticatedRouteRouteRoute._addFileChildren(
    AuthenticatedRouteRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRouteRoute: AuthenticatedRouteRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
